# Base image from node 19
FROM node:19 as build
# Working directory start at /app
WORKDIR /app
# Copy source code
COPY . .
# install dependentcy
RUN npm install
# build app
RUN npm run build:production

FROM nginx:1.19 as deploy

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html

# expose port 80 (configuration)
EXPOSE 80
# start the app
CMD [ "nginx", "-g", "daemon off;" ]